# Generated by Django 2.1.7 on 2019-03-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mpesaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessShortCode', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Timestamp', models.CharField(max_length=255)),
                ('TransactionType', models.CharField(max_length=255)),
                ('Amount', models.CharField(max_length=255)),
                ('PartyA', models.CharField(max_length=255)),
                ('PartyB', models.CharField(max_length=255)),
                ('CallBackURL', models.CharField(max_length=255)),
                ('AccountReference', models.CharField(max_length=255)),
                ('TransactionDesc', models.CharField(max_length=255)),
            ],
        ),
    ]
