# Generated by Django 2.1.7 on 2019-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesadetail',
            name='api_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
