# Generated by Django 2.1.7 on 2019-03-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0002_mpesadetail_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesadetail',
            name='Amount',
        ),
    ]
