# Generated by Django 2.1.7 on 2019-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0004_auto_20190314_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
