# Generated by Django 2.1.7 on 2019-03-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0005_payments_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payments',
            new_name='payment',
        ),
    ]
