# Generated by Django 2.1.7 on 2020-05-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0006_auto_20190314_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='CheckoutRequestID',
            field=models.CharField(default='', max_length=500),
        ),
    ]
