# Generated by Django 2.1.7 on 2020-05-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0007_payment_checkoutrequestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
